table upm_ecosys_ogepoexport
	excludeFromModelRefresh
	lineageTag: 8369cc35-a61b-4cae-b14e-f1077f77580d

	column Table
		dataType: string
		lineageTag: 88e6819f-7342-4efe-8b42-2f7669fa4ef6
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: double
		lineageTag: c265452c-ae71-4b5c-9a15-283bfaa53e25
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition upm_ecosys_ogepoexport = m
		mode: import
		source =
				let
				    Source = CommonDataService.Database("upm.crm.dynamics.com"),
				    dbo_upm_ecosys_ogepoexport = Source{[Schema="dbo",Item="upm_ecosys_ogepoexport"]}[Data],
				    #"Grouped Rows" = Table.Group(dbo_upm_ecosys_ogepoexport, {"upm_ecosys_ogepoexportid"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Table", each "upm_ecosys_ogepoexport"),
				    #"Grouped Rows1" = Table.Group(#"Added Custom", {"Table"}, {{"Count", each List.Sum([Count]), type number}})
				in
				    #"Grouped Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

