table upm_ecosys_ogedepolineitems
	excludeFromModelRefresh
	lineageTag: e988d5bf-851c-4d57-8786-7d4b9e618b5d

	column Table
		dataType: string
		lineageTag: f41b16b2-7f2b-4e9b-a6a2-561e035a9293
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: double
		lineageTag: eb52be8e-8818-4e93-8d1d-cbaae5374bee
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition upm_ecosys_ogedepolineitems = m
		mode: import
		source =
				let
				    Source = CommonDataService.Database("upm.crm.dynamics.com"),
				    dbo_upm_ecosys_ogedepolineitems = Source{[Schema="dbo",Item="upm_ecosys_ogedepolineitems"]}[Data],
				    #"Grouped Rows" = Table.Group(dbo_upm_ecosys_ogedepolineitems, {"upm_ecosys_ogedepolineitemsid"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Table", each "upm_ecosys_ogedepolineitems"),
				    #"Grouped Rows1" = Table.Group(#"Added Custom", {"Table"}, {{"Count", each List.Sum([Count]), type number}})
				in
				    #"Grouped Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

