table upm_transmissionplanlookupsppduid
	excludeFromModelRefresh
	lineageTag: 0c11d7af-d0b6-4048-8e08-71bc67c823fd

	column Table
		dataType: string
		lineageTag: 40cdf670-f091-4293-8525-2426392c8a6b
		summarizeBy: none
		sourceColumn: Table

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: double
		lineageTag: 85641bab-dcdc-4149-9566-27adea01b752
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition upm_transmissionplanlookupsppduid = m
		mode: import
		source =
				let
				    Source = CommonDataService.Database("upm.crm.dynamics.com"),
				    dbo_upm_transmissionplanlookupsppduid = Source{[Schema="dbo",Item="upm_transmissionplanlookupsppduid"]}[Data],
				    #"Grouped Rows" = Table.Group(dbo_upm_transmissionplanlookupsppduid, {"upm_transmissionplanlookupsppduidid"}, {{"Count", each Table.RowCount(_), Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Grouped Rows", "Table", each "upm_transmissionplanlookupsppduid"),
				    #"Grouped Rows1" = Table.Group(#"Added Custom", {"Table"}, {{"Count", each List.Sum([Count]), type number}})
				in
				    #"Grouped Rows1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

